import { Inter } from "next/font/google";
import "./globals.css";
import {
  AppSidebar,
  SidebarProvider,
  ThemeProvider,
} from "@/components";
import { TopBar } from "@/components";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="overflow-hidden">
            <SidebarProvider className="px-2">
              <AppSidebar />
              <div className="flex flex-col flex-1">
              
                <TopBar />

                {children}
              </div>
            </SidebarProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
